services:
  test:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /src
    privileged: true
    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true
      - type: volume
        source: maven-cache
        target: /root/.m2
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    entrypoint:
      [
        "mvn",
        "-Ptest",
        "clean",
        "test",
        "-DfailIfNoTests=false",
        "--no-transfer-progress",
      ]
    container_name: dogwalks-unit-test
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - JWT_SECRET=poeunhdyqbsjurkdoancnuendkaskdhejdsfwrgefmuweyf43x758jy
      - JWT_EXPIRATION=864000000
      - ADMIN_EMAIL=testadmin@test.com
      - ADMIN_PASSWORD=testAdminPsw547,
      - TESTCONTAINERS_RYUK_DISABLED=true
    restart: no

volumes:
  maven-cache:
    driver: local
