# Docker Compose configuration for app testing with Maven image
# This configuration runs tests using the official Maven Docker image
# without building a custom container image

services:
  # Test service using official Maven image
  test:
    # Use official Maven image with Eclipse Temurin JDK 21
    image: maven:3.9.11-eclipse-temurin-21

    # Set working directory inside container
    working_dir: /src

    # Mount source code as read-only volume for testing
    volumes:
      - type: bind
        source: . # Current directory (project root)
        target: /src # Mount point inside container
        read_only: true # Prevent modifications to source code

    # Run Maven test command with test profile
    # Using -Ptest profile to avoid building JAR files (allows read-only source mounting)
    entrypoint: ["mvn", "-Ptest", "clean", "verify", "--no-transfer-progress"]

    # Custom container name for easier identification
    container_name: dogwalks-unit-test

    # Environment variables passed to the SpringBoot application
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SERVER_PORT=8080 # Sets the server port inside container
      - JWT_SECRET=poeunhdyqbsjurkdoancnuendkaskdhejdsfwrgefmuweyf43x758jy
      - JWT_EXPIRATION=864000000
      - ADMIN_EMAIL=testadmin@test.com
      - ADMIN_PASSWORD=testAdminPsw547,

    # Restart policy - never restart (single-run test container)
    restart: no

    # Health check configuration for the SpringBoot application
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ] # Health check command
      interval: 30s # Check every 30 seconds
      timeout: 10s # Timeout after 10 seconds
      retries: 3 # Retry 3 times before marking as unhealthy
      start_period: 60s # Wait 60 seconds before starting health checks